image: python:latest
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
  paths:
    - .cache/pip
    - .tox
    - radloggerpy/locale
before_script:
  - pip install tox
stages:
  - linting
  - locale
  - unit-tests
  - documents
linting:
  stage: linting
  script:
    - tox -e pep8
locale:
  stage: locale
  script:
    - tox -e tenv python setup.py compile_catalog
unit_test_py36:
  stage: unit-tests
  script:
    - tox -e py36
unit_test_py39:
  stage: unit-tests
  script:
    - tox -e py39
unit_test_docker:
  stage: unit-tests
  image: python:3.9-buster
  tags:
    - docker
  script:
    - tox -e py39
docs:
  stage: documents
  script:
    - tox -e docs
config:
  stage: documents
  script:
    - tox -e genconfig
