image: python:latest
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  CODECOV_TOKEN: "ad646b4d-8d41-4b6c-912e-09a09ac2d097"
cache:
  paths:
    - .cache/pip
    - radloggerpy/locale
before_script:
  - pip install tox
stages:
  - linting
  - locale
  - unit-tests
  - coverage
  - documents
linting:
  stage: linting
  script:
    - tox -e pep8
locale:
  stage: locale
  script:
    # Enforce that pot file is up to date
    - tox -e tenv python setup.py compile_catalog
unit_test_py38:
  stage: unit-tests
  image: python:3.8-buster
  script:
    - tox -e py37
unit_test_py39:
  stage: unit-tests
  image: python:3.9-buster
  script:
    - tox -e py39
unit_test_py310:
  stage: unit-tests
  image: python:3.10-buster
  script:
    - tox -e py310
unit_test_py311:
  stage: unit-tests
  image: python:3.11-buster
  script:
    - tox -e py311
lower_constraints:
  stage: unit-tests
  image: python:3.8-buster
  script:
    - tox -e lower-constraints
coverage:
  stage: coverage
  script:
    - pip install codecov
    - tox -e cover
    - codecov
docs:
  stage: documents
  script:
    - tox -e docs
config:
  stage: documents
  script:
    - tox -e genconfig
