image: python:latest
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  CODECOV_TOKEN: "ad646b4d-8d41-4b6c-912e-09a09ac2d097"
cache:
  paths:
    - .cache/pip
before_script:
  - pip install tox
stages:
  - linting
  - locale
  - unit-tests
  - coverage
  - documents
pep8:
  stage: linting
  script:
    - tox -e pep8
pylint:
  stage: linting
  allow_failure: true
  script:
    - tox -e pylint
locale:
  stage: locale
  script:
    # Enforce that pot file is up to date
    - tox -e extract_messages
    - tox -e update_catalog
    - tox -e compile_catalog
  artifacts:
    paths:
      - locale/
    expire_in: 7 days
unit_test_py38:
  stage: unit-tests
  image: python:3.8-buster
  script:
    - tox -e py38
unit_test_py39:
  stage: unit-tests
  image: python:3.9-buster
  script:
    - tox -e py39
unit_test_py310:
  stage: unit-tests
  image: python:3.10-buster
  script:
    - tox -e py310
unit_test_py311:
  stage: unit-tests
  image: python:3.11-buster
  script:
    - tox -e py311
lower_constraints:
  stage: unit-tests
  image: python:3.8-buster
  script:
    - tox -e py38-lower-constraints
coverage:
  stage: coverage
  script:
    - pip install codecov
    - tox -e coverage
    - codecov -f coverage.xml
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
    paths:
      - htmlcov/*
    expire_in: 7 days
docs:
  stage: documents
  script:
    - tox -e docs
config:
  stage: documents
  script:
    - tox -e genconfig
