image: python:latest
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  CODECOV_TOKEN: "ad646b4d-8d41-4b6c-912e-09a09ac2d097"
cache:
  paths:
    - .cache/pip
    - .tox
    - radloggerpy/locale
before_script:
  - pip install tox
stages:
  - linting
  - locale
  - unit-tests
  - coverage
  - documents
linting:
  stage: linting
  script:
    - tox -e pep8
type_checking:
  stage: linting
  allow_failure: true
  script:
    - tox -e typecheck
locale:
  stage: locale
  script:
    - tox -e tenv python setup.py compile_catalog
#locale_docker:
#  stage: locale
#  image: python:3.9-buster
#  tags:
#    - docker
#  script:
#    - tox -e tenv python setup.py compile_catalog
unit_test_py36:
  stage: unit-tests
  image: python:3.6-buster
  script:
    - tox -e py36
unit_test_py39:
  stage: unit-tests
  image: python:3.9-buster
  script:
    - tox -e py39
#unit_test_docker:
#  stage: unit-tests
#  image: python:3.9-buster
#  tags:
#    - docker
#  script:
#    - tox -e py39
coverage:
  stage: coverage
  script:
    - pip install codecov
    - tox -e cover
    - codecov
docs:
  stage: documents
  script:
    - tox -e docs
config:
  stage: documents
  script:
    - tox -e genconfig
