language: python
python:
  - "2.7"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install tox
script:
  - tox -e pep8
  - tox -e cover
  - tox -e docs