language: python
# To ensure caches are accessible between staged jobs they need to have the
# following attributes be identical:
#   - os name (linux, osx, windows)
#   - os distribution (xenial, trusty)
#   - osx image (xcode7.2)
#   - environment variables (CODECOV_TOKEN)
#   - language runtime (python: "3.8")
# Failure to have all of these attributes identical will result in separate
# caches and files not being available between jobs & stages!
# Travis offers no method to override how caches are shared.
cache:
  directories:
  - radloggerpy/locale
env:
  - CODECOV_TOKEN="ad646b4d-8d41-4b6c-912e-09a09ac2d097"
jobs:
  include:
    - stage: linting
      name: "Linting"
      python:
        - "3.8"
      install:
        - pip install tox
      script:
        - tox -e pep8
    - stage: locale
      name: "Locale py36"
      python:
        - "3.6"
      install:
        - pip install tox
      script:
        - tox -e tenv python setup.py compile_catalog
    - stage: locale
      name: "Locale py37"
      python:
        - "3.7"
      install:
        - pip install tox
      script:
        - tox -e tenv python setup.py compile_catalog
    - stage: locale
      name: "Locale py38"
      python:
        - "3.8"
      install:
        - pip install tox
      script:
        - tox -e tenv python setup.py compile_catalog
    - stage: locale
      name: "Locale py39"
      python:
        - "3.9"
      install:
        - pip install tox
      script:
        - tox -e tenv python setup.py compile_catalog
    - stage: test
      name: "Unit test py36"
      python:
        - "3.6"
      install:
        - pip install tox
      script:
        - tox -e py36
    - stage: test
      name: "Unit test py37"
      python:
        - "3.7"
      install:
        - pip install tox
      script:
        - tox -e py37
    - stage: test
      name: "Unit test py38"
      python:
        - "3.8"
      install:
        - pip install tox
      script:
        - tox -e py38
    - stage: test
      name: "Unit test py39"
      python:
        - "3.9"
      install:
        - pip install tox
      script:
        - tox -e py39
    - stage: cover
      name: "Coverage report"
      python:
        - "3.8"
      install:
        - pip install tox
        - pip install codecov
      script:
        - tox -e cover
      after_success:
        - codecov
    - stage: docs
      name: "Sphinx documentation"
      if: branch = master OR type = pull_request
      python:
        - "3.8"
      install:
        - pip install tox
      script:
        - tox -e docs
#    - stage: docs
#      name: "Releasenotes"
#      if: branch = master OR type = pull_request
#      python:
#        - "3.7"
#      install:
#        - pip install tox
#      script:
#        - tox -e releasenotes
    - stage: docs
      name: "Generated configuration"
      if: branch = master OR type = pull_request
      python:
        - "3.8"
      install:
        - pip install tox
      script:
        - tox -e genconfig
