language: python
jobs:
  include:
    - stage: testpy27
      python:
        - "2.7"
      install:
        - pip install tox
      script:
        - tox -e py27
    - stage: testpy37
      python:
        - "3.6"
      install:
        - pip install tox
      script:
        - tox -e py36
    - stage: testpy37
      python:
        - "3.7"
      install:
        - pip install tox
      script:
        - tox -e py37
    - stage: cover
      python:
        - "3.7"
      install:
        - pip install tox
      script:
        - tox -e cover
    - stage: docs
      python:
        - "3.7"
      install:
        - pip install tox
      script:
        - tox -e docs