[build-system]
requires = [
    "setuptools>=45,<68",
    "setuptools_scm[toml]>=6.2",
    "wheel"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "radloggerpy/_version.py"

[tool.pylint]
ignore = "_version.py"
